version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: nhs-waitlist-db
    environment:
      POSTGRES_DB: nhs_waitlist
      POSTGRES_USER: nhs_user
      POSTGRES_PASSWORD: nhs_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nhs_user -d nhs_waitlist"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - nhs-network

volumes:
  postgres_data:
    driver: local

networks:
  nhs-network:
    driver: bridge
